const fs = require('fs');
const path = 'o:\\OneDrive\\Business\\Development\\Whatsapp Api + CRM (19 March 2026)\\frontend\\src\\pages\\Contacts.jsx';
const content = fs.readFileSync(path, 'utf8');
const lines = content.split('\n');
const healthyLines = lines.slice(0, 1107);
healthyLines.push('               <form onSubmit={handleAddContact} className=\"space-y-8\">');
healthyLines.push('                  <div className=\"space-y-2\">');
healthyLines.push('                     <label className=\"text-[11px] font-black text-slate-400 uppercase tracking-[0.3em] ml-2\">Identity Signature</label>');
healthyLines.push('                     <input autoFocus type=\"text\" value={newLeadName} onChange={e=>setNewLeadName(e.target.value)} required className=\"w-full bg-[#f9fafb] border border-slate-100 rounded-[2rem] px-7 py-5 outline-none focus:ring-4 focus:ring-[var(--theme-border)]/10 focus:border-[var(--theme-border)]/50 text-base font-bold text-slate-800 transition-all shadow-sm\" placeholder=\"Full name profile\" />');
healthyLines.push('                  </div>');
healthyLines.push('                  <div className=\"space-y-2\">');
healthyLines.push('                     <label className=\"text-[11px] font-black text-slate-400 uppercase tracking-[0.3em] ml-2\">Communication Hub</label>');
healthyLines.push('                     <input type=\"tel\" value={newLeadPhone} onChange={e=>setNewLeadPhone(e.target.value)} required className=\"w-full bg-[#f9fafb] border border-slate-100 rounded-[2rem] px-7 py-5 outline-none focus:ring-4 focus:ring-[var(--theme-border)]/10 focus:border-[var(--theme-border)]/50 text-base font-bold text-slate-800 transition-all shadow-sm\" placeholder=\"+91 XXX XXX XXXX\" />');
healthyLines.push('                  </div>');
healthyLines.push('                  <button type=\"submit\" className=\"w-full py-6 bg-slate-900 text-white text-[12px] font-black uppercase tracking-[0.4em] rounded-[2rem] shadow-3xl hover:-translate-y-2 active:scale-95 transition-all mt-4\">Establish Profile</button>');
healthyLines.push('               </form>');
healthyLines.push('            </div>');
healthyLines.push('         </div>');
healthyLines.push('       )}');
healthyLines.push('');
healthyLines.push('      {/* UNIFIED BULK ACTIONS BAR */}');
healthyLines.push('      {selectedIds.size > 0 && (');
healthyLines.push('         <div className=\"fixed bottom-10 left-1/2 -translate-x-1/2 z-[999] bg-slate-900/95 text-white rounded-[2.5rem] px-8 py-5 shadow-3xl flex items-center space-x-10 animate-slide-up border border-white/10 backdrop-blur-md\">');
healthyLines.push('            <div className=\"flex items-center space-x-4 pr-10 border-r border-white/10\">');
healthyLines.push('               <div className=\"w-12 h-12 bg-teal-500 rounded-2xl flex items-center justify-center text-white shadow-glow animate-pulse\">');
healthyLines.push('                  <Target size={24} />');
healthyLines.push('               </div>');
healthyLines.push('               <div>');
healthyLines.push('                  <p className=\"text-[10px] font-black uppercase tracking-[0.2em] text-teal-400 mb-1\">{selectedIds.size} Leads Selected</p>');
healthyLines.push('                  <p className=\"text-sm font-black uppercase tracking-widest\">{isBulkUpdating ? \"Executing Command...\" : \"Workspace Batch\"}</p>');
healthyLines.push('               </div>');
healthyLines.push('            </div>');
healthyLines.push('');
healthyLines.push('            <div className=\"flex items-center space-x-6\">');
healthyLines.push('               {/* TRANSFER AGENT */}');
healthyLines.push('               <div className=\"flex flex-col space-y-1\">');
healthyLines.push('                  <label className=\"text-[9px] font-black text-white/40 uppercase tracking-widest ml-1\">Assign Agent</label>');
healthyLines.push('                  <div className=\"flex items-center bg-white/5 rounded-2xl p-1 border border-white/10\">');
healthyLines.push('                     <select value={bulkTargetAgent} onChange={(e) => setBulkTargetAgent(e.target.value)} className=\"bg-transparent text-[11px] font-bold px-4 py-2 outline-none cursor-pointer text-white min-w-[160px]\">');
healthyLines.push('                        <option value=\"\" className=\"text-slate-900\">Choose Agent...</option>');
healthyLines.push('                        {agents.map(a => <option key={a._id} value={a._id} className=\"text-slate-900\">{a.name}</option>)}');
healthyLines.push('                     </select>');
healthyLines.push('                     <button disabled={!bulkTargetAgent || isBulkUpdating} onClick={() => handleBulkAction(\"transfer_leads\", bulkTargetAgent)} className=\"bg-teal-500 hover:bg-teal-600 disabled:bg-slate-700 p-2.5 rounded-xl transition-all shadow-lg active:scale-95 text-white\">');
healthyLines.push('                        <ArrowUpRight size={18} />');
healthyLines.push('                     </button>');
healthyLines.push('                  </div>');
healthyLines.push('               </div>');
healthyLines.push('');
healthyLines.push('               {/* TRANSFER COUNSELLOR */}');
healthyLines.push('               <div className=\"flex flex-col space-y-1\">');
healthyLines.push('                  <label className=\"text-[9px] font-black text-white/40 uppercase tracking-widest ml-1\">Assign Counsellor</label>');
healthyLines.push('                  <div className=\"flex items-center bg-white/5 rounded-2xl p-1 border border-white/10\">');
healthyLines.push('                     <select value={bulkTargetCounsellor} onChange={(e) => setBulkTargetCounsellor(e.target.value)} className=\"bg-transparent text-[11px] font-bold px-4 py-2 outline-none cursor-pointer text-white min-w-[160px]\">');
healthyLines.push('                        <option value=\"\" className=\"text-slate-900\">Choose Expert...</option>');
healthyLines.push('                        {agents.filter(a => a.role === \"MANAGER_COUNSELLOUR\" || a.role === \"ADMIN\").map(a => (<option key={a._id} value={a._id} className=\"text-slate-900\">{a.name}</option>))}');
healthyLines.push('                     </select>');
healthyLines.push('                     <button disabled={!bulkTargetCounsellor || isBulkUpdating} onClick={() => handleBulkAction(\"transfer_counsellor\", bulkTargetCounsellor)} className=\"bg-blue-500 hover:bg-blue-600 disabled:bg-slate-700 p-2.5 rounded-xl transition-all shadow-lg active:scale-95 text-white\">');
healthyLines.push('                        <Headphones size={18} />');
healthyLines.push('                     </button>');
healthyLines.push('                  </div>');
healthyLines.push('               </div>');
healthyLines.push('');
healthyLines.push('               {/* STAGE COMMAND */}');
healthyLines.push('               <div className=\"flex flex-col space-y-1\">');
healthyLines.push('                  <label className=\"text-[9px] font-black text-white/40 uppercase tracking-widest ml-1\">Move Stage</label>');
healthyLines.push('                  <div className=\"flex items-center bg-white/5 rounded-2xl p-1 border border-white/10\">');
healthyLines.push('                     <select onChange={(e) => handleBulkAction(\"update_stage\", e.target.value)} className=\"bg-transparent text-[11px] font-bold px-4 py-2 outline-none cursor-pointer text-white min-w-[130px]\" defaultValue=\"\">');
healthyLines.push('                        <option value=\"\" disabled className=\"text-slate-900\">Pipeline Stage...</option>');
healthyLines.push('                        {PIPELINE_STAGES.map(s => <option key={s} value={s} className=\"text-slate-900\">{s}</option>)}');
healthyLines.push('                     </select>');
healthyLines.push('                  </div>');
healthyLines.push('               </div>');
healthyLines.push('');
healthyLines.push('               <div className=\"w-[1px] h-10 bg-white/10 mx-2\"></div>');
healthyLines.push('');
healthyLines.push('               <div className=\"flex items-center space-x-3\">');
healthyLines.push('                  <button onClick={handleExportCSV} className=\"p-4 hover:bg-white/10 rounded-2xl transition-all text-white/60 hover:text-white\" title=\"Export Set\"><Download size={20} /></button>');
healthyLines.push('                  <button onClick={() => handleBulkAction(\"archive_leads\", true)} className=\"p-4 hover:bg-orange-500/20 text-orange-400 rounded-2xl transition-all\" title=\"Archive Leads\"><ShieldCheck size={20}/></button>');
healthyLines.push('                  <button onClick={() => { if(window.confirm(`Delete ${selectedIds.size} leads permanently?`)) handleBulkAction(\"hard_delete_leads\", {}); }} className=\"p-4 hover:bg-red-500/20 text-red-400 rounded-2xl transition-all font-bold text-lg\"><MoreVertical size={20} /></button>');
healthyLines.push('               </div>');
healthyLines.push('            </div>');
healthyLines.push('            ');
healthyLines.push('            <button onClick={() => setSelectedIds(new Set())} className=\"ml-6 p-4 hover:bg-white/10 text-white/20 hover:text-white rounded-2xl transition-all border border-transparent hover:border-white/10\">');
healthyLines.push('               <X size={24} />');
healthyLines.push('            </button>');
healthyLines.push('         </div>');
healthyLines.push('      )}');
healthyLines.push('    </div>');
healthyLines.push('  );');
healthyLines.push('}');
fs.writeFileSync(path, healthyLines.join('\n'));
